server:
  port: 9000
  servlet:
    context-path: /manager

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: Karry0921
    url: jdbc:mysql://bj.kevinkda.cn:3306/university?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&useUnicode=true&useSSL=true&allowPublicKeyRetrieval=true
    username: kevin
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:


## 生成的公钥
#public-key: 这里添生成的公钥
## 配置 connection-properties，启用加密，配置公钥。
#spring.datasource.druid.connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
